apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 17
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            command: ["sh"]
            args:
            - -c
            - "date; echo Hello from the Kubernetes cluster"
          restartPolicy: Never